"""add github integration tables

Revision ID: 23a611a1c53e
Revises: a1b2c3d4e5f6
Create Date: 2026-04-04 17:48:21.169200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '23a611a1c53e'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysisjob',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('current_step_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysisjob_user_id'), 'analysisjob', ['user_id'], unique=False)
    op.create_table('contributioncache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_contributions', sa.Integer(), nullable=False),
    sa.Column('total_commits', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('calendar_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cached_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contributioncache_user_id'), 'contributioncache', ['user_id'], unique=True)
    op.create_table('githubprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('github_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('github_access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('github_avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('github_bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('public_repos_count', sa.Integer(), nullable=False),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('github_created_at', sa.DateTime(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('last_analyzed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_githubprofile_github_username'), 'githubprofile', ['github_username'], unique=False)
    op.create_index(op.f('ix_githubprofile_user_id'), 'githubprofile', ['user_id'], unique=True)
    op.create_table('repositorycache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repo_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repo_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('primary_language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('languages_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topics_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dependencies_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stargazer_count', sa.Integer(), nullable=False),
    sa.Column('fork_count', sa.Integer(), nullable=False),
    sa.Column('commit_count', sa.Integer(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('pushed_at', sa.DateTime(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositorycache_user_id'), 'repositorycache', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repositorycache_user_id'), table_name='repositorycache')
    op.drop_table('repositorycache')
    op.drop_index(op.f('ix_githubprofile_user_id'), table_name='githubprofile')
    op.drop_index(op.f('ix_githubprofile_github_username'), table_name='githubprofile')
    op.drop_table('githubprofile')
    op.drop_index(op.f('ix_contributioncache_user_id'), table_name='contributioncache')
    op.drop_table('contributioncache')
    op.drop_index(op.f('ix_analysisjob_user_id'), table_name='analysisjob')
    op.drop_table('analysisjob')
    # ### end Alembic commands ###
