"""Add roadmap_cache table

Revision ID: 4907b9d51769
Revises: 44aacc31e4cd
Create Date: 2026-04-15 09:17:31.695744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4907b9d51769'
down_revision: Union[str, Sequence[str], None] = '44aacc31e4cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_slug', sa.String(), nullable=False),
    sa.Column('nodes_json', sa.String(), nullable=False),
    sa.Column('cached_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_cache_career_slug'), 'roadmap_cache', ['career_slug'], unique=True)
    # Note: career_reports.progression_json type change from TEXT to VARCHAR is a no-op in
    # PostgreSQL (both are stored the same way), but we include it for schema consistency.
    op.alter_column('career_reports', 'progression_json',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('career_reports', 'progression_json',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_roadmap_cache_career_slug'), table_name='roadmap_cache')
    op.drop_table('roadmap_cache')
    # ### end Alembic commands ###
