"""add pipeline_jobs and career_reports tables

Revision ID: 7541c710f98d
Revises: 13ca9a4e6042
Create Date: 2026-04-07 10:56:08.941285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7541c710f98d'
down_revision: Union[str, Sequence[str], None] = '13ca9a4e6042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
