"""add_advisor_id_to_user

Revision ID: c2ba04c1cb25
Revises: 0d3b5a615b5d
Create Date: 2026-05-26 04:54:05.796636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2ba04c1cb25'
down_revision: Union[str, Sequence[str], None] = '0d3b5a615b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('advisor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'instructor', ['advisor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'advisor_id')
    # ### end Alembic commands ###
