"""Add activities_json to ContributionCache

Revision ID: c88e066d8fbc
Revises: 7541c710f98d
Create Date: 2026-04-08 19:31:52.405074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c88e066d8fbc'
down_revision: Union[str, Sequence[str], None] = '7541c710f98d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributioncache', sa.Column('activities_json', sqlmodel.sql.sqltypes.AutoString(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contributioncache', 'activities_json')
    # ### end Alembic commands ###
