import sqlmodel
"""add_github_skill_cache

Revision ID: d0bc1d263d8d
Revises: 36712b2dcc6b
Create Date: 2026-05-10 14:45:46.235342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0bc1d263d8d'
down_revision: Union[str, Sequence[str], None] = '36712b2dcc6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_skill_cache',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('data_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('github_skills', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_index(op.f('ix_github_skill_cache_data_hash'), 'github_skill_cache', ['data_hash'], unique=False)
    op.drop_index(op.f('ix_student_interventions_student_id'), table_name='student_interventions')
    op.drop_table('student_interventions')
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.alter_column('chat_sessions', 'label',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_chat_sessions_student_id'), table_name='chat_sessions')
    op.create_index(op.f('ix_chat_sessions_label'), 'chat_sessions', ['label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_label'), table_name='chat_sessions')
    op.create_index(op.f('ix_chat_sessions_student_id'), 'chat_sessions', ['student_id'], unique=False)
    op.alter_column('chat_sessions', 'label',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.alter_column('chat_messages', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('student_interventions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interventions_json', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('student_interventions_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('student_interventions_pkey'))
    )
    op.create_index(op.f('ix_student_interventions_student_id'), 'student_interventions', ['student_id'], unique=True)
    op.drop_index(op.f('ix_github_skill_cache_data_hash'), table_name='github_skill_cache')
    op.drop_table('github_skill_cache')
    # ### end Alembic commands ###
